require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 3
